### PR TITLE
Rubocop

### PR DESCRIPTION
**Pull request by williamcodes**

### CODE REVIEW

**Comment by oliverbarnes** [comment]
hound will quickly drive you nuts heheh... I'd suggest just adding rubocop to guard and travis, tis plenty

**Comment by williamcodes** [comment]
Yeah hound is a bitch. It is really cathartic to yell at though. What's the advantage of adding Rubocop to Travis? I would think that'd have the same effect.

**Comment by oliverbarnes** [comment]
heheheh, maybe hounci should be renamed...

same effect in keeping merges from happening unless rubocop is happy, but without the noise on pull request comments. you only see that travis failed, and when checking the build you'll see the compiled list of rubocop offenses. 

that would be just for safety from contributors not running rubocop locally, which is the ideal. Hence my suggestion to add `guard-rubocop`. be sure to [configure it so it only runs once your tests are passing](https://github.com/oliverbarnes/participate-api/blob/master/Guardfile), else you'll find yourself serially catharting and will soon become known as Howling Will from Civic Hall. Or Catharting Bill

("Catharting" has double meaning, btw. Worth googling it)

**Comment by williamcodes** [comment]
hahahahahahaha

**Pull request merged**
